import { config } from "dotenv";
config();

const {
  NODE_ENV = "development",
  APP_PORT = 5500,

  GOOGLE_CALLBACK_URL = "http://localhost:5088/api/v1/auth/google/callback",

  GOOGLE_CLIENT_SECRET = "DEFAULT_GOOGLE_CLIENT_SECRET",
  GOOGLE_CLIENT_ID = "DEFAULT_GOOGLE_CLIENT_ID",

  SESSION_SECRET_KEY = "DEFAULT_SESSION_SECRET_KEY",
  ACCESS_TOKEN_SECRET = "DEFAULT_ACCESS_TOKEN_SECRET",

  DB_HOST = "ocalhost",
  DB_PORT = "5435",
  DB_NAME = "postgres",
  DB_USER = "postgres",
  DB_PASSWORD = "postgres",
  DB_MAX_CONNECTIONS = "20",
  DB_IDLE_TIMEOUT = "30000",
  DB_CONNECTION_TIMEOUT = "2000",
} = process.env;

const ENV = {
  NODE_ENV,
  APP_PORT,

  GOOGLE_CALLBACK_URL,

  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,

  SESSION_SECRET_KEY,
  ACCESS_TOKEN_SECRET,

  DB_HOST,
  DB_PORT,
  DB_NAME,
  DB_USER,
  DB_PASSWORD,
  DB_MAX_CONNECTIONS,
  DB_IDLE_TIMEOUT,
  DB_CONNECTION_TIMEOUT,
};

export { ENV };
