import { config } from "dotenv";
config();

const {
  NODE_ENV = "development",
  APP_PORT = 5500,

  FILE_SIZE = "52428800",

  FRONTEND_URL = "http://localhost:5555",
  GOOGLE_CALLBACK_URL = "http://localhost:5088/api/v1/auth/google/callback",

  GOOGLE_CLIENT_SECRET = "DEFAULT_GOOGLE_CLIENT_SECRET",
  GOOGLE_CLIENT_ID = "DEFAULT_GOOGLE_CLIENT_ID",

  GCLOUD_PROJECT_ID = "",
  GCLOUD_BUCKET_NAME = "",
  GCLOUD_FOLDER_NAME = "",
  GCS_SERVICE_ACCOUNT = "",

  RABBITMQ_EXCHANGE = "",
  RABBITMQ_MAIN_QUEUE = "",
  RABBITMQ_RETRY_QUEUE = "",
  RABBITMQ_DL_QUEUE = "",

  RABBITMQ_USERNAME = "",
  RABBITMQ_PASSWORD = "",
  RABBITMQ_VHOST = "",
  RABBITMQ_HOST = "",
  RABBITMQ_PORT = "",

  SESSION_SECRET_KEY = "DEFAULT_SESSION_SECRET_KEY",
  ACCESS_TOKEN_SECRET = "DEFAULT_ACCESS_TOKEN_SECRET",

  MONGODB_URL = "mongodb://localhost:27017/mongodb-test",
} = process.env;

const ENV = {
  NODE_ENV,
  APP_PORT,

  FILE_SIZE,

  FRONTEND_URL,
  GOOGLE_CALLBACK_URL,

  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,

  GCLOUD_PROJECT_ID,
  GCLOUD_BUCKET_NAME,
  GCLOUD_FOLDER_NAME,
  GCS_SERVICE_ACCOUNT,

  RABBITMQ_EXCHANGE,
  RABBITMQ_MAIN_QUEUE,
  RABBITMQ_RETRY_QUEUE,
  RABBITMQ_DL_QUEUE,

  RABBITMQ_USERNAME,
  RABBITMQ_PASSWORD,
  RABBITMQ_VHOST,
  RABBITMQ_HOST,
  RABBITMQ_PORT,

  SESSION_SECRET_KEY,
  ACCESS_TOKEN_SECRET,

  MONGODB_URL,
};

export { ENV };
